"""create table

Revision ID: 2026_03_02_22_32_47_274
Revises: 
Create Date: 2026-03-02 22:32:47.283427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2026_03_02_22_32_47_274'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transaction', 'person', ['person_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', schema='public', type_='foreignkey')
    op.drop_column('transaction', 'person_id')
    # ### end Alembic commands ###
