"""update transaction

Revision ID: 2026_03_02_22_33_05_102
Revises: 2026_03_02_22_32_47_274
Create Date: 2026-03-02 22:33:05.113468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2026_03_02_22_33_05_102'
down_revision: Union[str, None] = '2026_03_02_22_32_47_274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transaction_person_id_fkey'), 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'person', ['person_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_person_id_fkey'), 'transaction', 'person', ['person_id'], ['id'])
    # ### end Alembic commands ###
